name: Build and deploy container app to Azure Web App - reptrackdep

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Debug working directory
      run: ls -al ./backend

    - name: Set up Docker Buildx
      working-directory: ./backend
      uses: docker/setup-buildx-action@v2

    - name: Log in to Azure Container Registry
      working-directory: ./backend
      uses: docker/login-action@v2
      with:
        registry: https://reptrackdep.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_c86dda1ba6a141c0ae1a438cb5d60068 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_9a286413e832450e9b7167bdc3ace4bd }}

    - name: Build and push container image to Azure Container Registry
      working-directory: ./backend
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: reptrackdep.azurecr.io/reptrackdep/v500:${{ github.sha }}
        file: ./backend/Dockerfile
        context: ./backend

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'reptrackdep'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_967b784af647408e9f1020e0eeb00919 }}
        images: 'reptrackdep.azurecr.io/reptrackdep/v500:${{ github.sha }}'
